# This is a basic workflow to help you get started with Actions

name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - uses: github/pvt-action@main
